version: "3"

volumes:
  mongodb_volume:

services:
  zebra:
    build: ./
    restart: always
    volumes:
      - ${LocationImage}:${LocationImage}
      - ${LocationQr}:${LocationQr}
      - ${LocationMenuItems}:${LocationMenuItems}
    ports:
      - 4000:4000
      - 8080:8080
    environment:
      - MONGO_HOST=mongodb://mongodb:27017

  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - mongodb_volume:/data/db
    restart: always